#!/bin/bash

err() {
  local color="\033[0;31m" #red
  local nc="\033[0m"
  echo "$color" "Valheim Script Error: $* $nc" >>/dev/stderr
}

info() {
  local color="\033[0;32m" #green
  local nc="\033[0m"
  echo "$color" "$* $nc"
}

titlebox() {
  local color="\033[0;33m" #yellow
  local nc="\033[0m"
  local s="$*"
  echo "
__${s//?/_}__
|$color $s $nc|
‾‾${s//?/‾}‾‾
"
}

#todo welcome + add to path help
#todo install
#todo start/stop/restart
#todo update
#todo backup daily|weekly|monthly on|off
#todo backup log
#todo backup cd